SELECT * FROM CHARACTER_SETS;
SELECT * FROM COLLATIONS;

CREATE DATABASE FACULDADE
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

USE FACULDADE;

CREATE TABLE tbAlunos (
	rgm INT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR (50) NOT NULL,
    data_nascimento DATE NOT NULL
	);
    
